### ISSUE TITLE
Tool does not work in Confluence if Page Layouts are activated

### ISSUE THREAD

**Issue by b-vermes** [grantwinney/generate-links-for-headers-in-chrome#11]
[This page crated in Confluence](https://experts.missouristate.edu/display/KB/Knowledge+Base+Style+Guide) has [Page Layouts](https://confluence.atlassian.com/doc/page-layouts-columns-and-sections-275188613.html) applied on. Links are generated for all the page name and headings but the icon is displayed and usable only for the page name.

**Comment by grantwinney** [comment]
That's odd. I can't figure out why it's happening there, but it probably happens on other sites too.

I moved the icon so it appears on the right side of the image instead of the left, which should always show. 🤞

Try updating the extension (the version is 1.2.5.. you might have to enable developer mode so you can see the update button), and see if the links appear. It's working for me now, but let me know if you run into any other problems.

**Comment by b-vermes** [comment]
Works well, thanks!
