### ISSUE TITLE
Add Popup Outline Showing All Links Found/Made

### ISSUE THREAD

**Issue by WHiZSTA** [grantwinney/generate-links-for-headers-in-chrome#22]
I'm not sure if the plugin just isn't working or what, but I've tried it on 3 diff sites with it not working at all. I figured a popup showing all the headers with links it finds/creates to them would be good to let you know if it even worked by showing results, and easily hop around/decide what link to copy. Likewise per your other idea, if nothing shows, it would let us know there is an issue and could give an option to report it.

The sites i tried it on are:
[World Population Review](https://worldpopulationreview.com/countries/united-states-population)
[AHA](https://www.heart.org/en/news/2022/08/22/covid-19-infection-poses-higher-risk-for-myocarditis-than-vaccines)
[CNN](https://www.cnn.com/europe/live-news/russia-ukraine-war-news-08-29-22/h_52d9a059a8e55bb86fdb120a2c2b068b)

**Comment by grantwinney** [comment]
Yikes, I completely missed this issue somehow, sorry. The reason it doesn't work on those sites is because they didn't bother to apply an `id` or `name` property to their headers, so there's no way to identify them and no way to create a direct link to them.

![image](https://github.com/user-attachments/assets/761259f3-0fbb-44a3-9af3-3fcc5a9bfcd6)

&nbsp;
&nbsp;

![image](https://github.com/user-attachments/assets/d7341ec6-ecc3-4fde-b4b8-aa82f8d3a04d)
